name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-graalvm:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        graal_version: [ '11', '17' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.graal_version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          lein: 2.9.1
      - name: Run unit tests
        run: lein test

  test-jvm:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java_version: [ '8', '11', '17', '20' ]
        java: [ 'zulu' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.java_version }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          lein: 2.9.1
      - name: Run unit tests
        run: lein test
