name: release
on:
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java_version: [ '20' ]
        java: [ 'zulu' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java }}
          java-version: ${{ matrix.java_version }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          lein: 2.9.1
      - name: set git user mail
        run: git config --global user.email "<>"
      - name: set git user name
        run: git config --global user.name "$GITHUB_TRIGGERING_ACTOR"
      - name: release product
        run: lein release
      - name: git push commit
        run: git push origin main
permissions:
  contents: write
